SELECT *
  FROM [BookingData]


  DELETE FROM BookingData
  WHERE Revenue = 5400

  DELETE FROM BookingData 
  WHERE Guests = 10 

  DELETE FROM BookingData
  WHERE Guests = 12

  DELETE FROM BookingData
  WHERE [Distribution Channel] = 'UNDEFINED'



-- AIM: THE AIM THIS ANALYSIS IS TO ANALYZE WHICH HOTEL TYPE IS PERFORMING WELL IN TERMS OF BOOKINGS AND REVENUE, AS WELL AS INDICATING THE FACTORS DIRECTLY AFFECTING THE REVENUE OF EACH HOTEL TYPE.
	--  ALSO, THE ORGANIZATION NEEDS TO UNDERSTAND THE BOOKING PATTERN FOR EACH CUSTOMER TYPE
-- OBJECTIVES 

--FIRST WE HAVE TO SEE THE TOTAL NUMBER OF BOOKINGS
	SELECT COUNT([BOOKING DATE]) TOTALBOOKING
	FROM BookingData

--WHAT IS THE TOTAL REVENUE GENERATED, AS WELL AS THE TOAL REVENUE LOSS
	SELECT ROUND(SUM(REVENUE), 2) TOTAL_REVENUE
	FROM BookingData

	SELECT ROUND(SUM([Revenue Loss]), 2) TOTAL_REVENUE_LOSS
	FROM BookingData

--TOTAL NIGHTS SPENT BY CUSTOMERS
	SELECT SUM(NIGHTS) TOTAL_NIGHTS
	FROM BookingData
	
--HOW MANY BOOKINGS WERE MADE ACCROSS EACH YEAR
	SELECT DISTINCT(YEARS), 
	SUM(YEARLY) TOTAL_BOOKING
	FROM
	(SELECT YEAR([Booking Date]) YEARS,
	COUNT (*) YEARLY
	FROM BookingData
	GROUP BY [Booking Date])
	BOOKING
	GROUP BY YEARS
	ORDER BY TOTAL_BOOKING DESC;

--MOST REVENUE BY YEAR
	WITH YEARLY_REV AS
	(SELECT YEAR([BOOKING DATE]) YEARLY,
	SUM(REVENUE) TOTALREV
	FROM BookingData
	GROUP BY [Booking Date])
	SELECT YEARLY, ROUND(SUM(TOTALREV), 0) SUM_OF_REV
	FROM YEARLY_REV
	GROUP BY YEARLY
	ORDER BY SUM_OF_REV DESC;

--MOST REVENUE LOSS BY YEAR
	WITH YEARLY_REV AS
	(SELECT YEAR([BOOKING DATE]) YEARLY,
	SUM([Revenue Loss]) REV_LOSS
	FROM BookingData
	GROUP BY [Booking Date])
	SELECT YEARLY, ROUND(SUM(REV_LOSS), 0) SUM_OF_REVLOSS
	FROM YEARLY_REV
	GROUP BY YEARLY
	ORDER BY SUM_OF_REVLOSS;

--CANCELATION BY YEAR
	WITH YEARLY_REV AS
	(SELECT YEAR([BOOKING DATE]) YEARLY,
	[Cancellation Status],
	COUNT(*) TOTAL_CANCELLATION
	FROM BookingData
	GROUP BY [Booking Date], [Cancellation Status])
	SELECT YEARLY, [Cancellation Status], SUM(TOTAL_CANCELLATION) SUM_OF_CANCELLATION
	FROM YEARLY_REV
	GROUP BY YEARLY, [Cancellation Status]
	ORDER BY YEARLY;

--SINCE WE ARE ANALYZING FOR HOTEL TYPE, OUR NEXT QUESTION IS, WHICH OF THE HOTEL TYPE CUSTOMERS TEND TO BOOK THE MORE, I.E THE BOOKING FREQUENCY OF EACH HOTEL TYPE
	SELECT Hotel, 
	COUNT(*) BOOKINGFREQ
	FROM BookingData
	GROUP BY Hotel
	ORDER BY BOOKINGFREQ DESC;

--FROM THE ABOVE, WE OBSERVE THAT CUSTOMERS TEND TO BOOK THE CITY HOTEL TYPE. MERELY LOOING AT THIS, WE MIGHT WANT TO BE BELIEVE THAT THE CITY HOTEL TYPE BRINGS IN MORE REVENUE, BUT LET'S 
--CONFIRM THIS, BY CALCULATING BOTH REVENUE AND REVENUE LOSS FOR EACH HOTEL TYPE

--WHAT HOTEL TYPE BRINGS MORE REVENUE, AND WHERE WERE LOSSES INCURRED THE MOST
	SELECT Hotel, 
	ROUND(SUM(REVENUE), 0) HOTELREV,
	ROUND(SUM([Revenue Loss]), 0) REV_LOSS
	FROM BookingData
	GROUP BY Hotel
	ORDER BY HOTELREV DESC;

--FROM WHAT WE HAVE SEEN FROM THE ABOVE, WE CAN SEE THAT THE CITY HAS QUITE MRE REVENUE THAN THE RESORT, ALSO, THE LOSSES INCURRED BY CITY WAS MUCH MORE THAN THE RESORT. WHAT COULD BE THE CAUSE OF THIS LOSS?? OHH, CANCELLATION STATUS NEEDS TO BE CHECKED.
--BUT BEFORE ANALYZING FOR THE CANCELLATION STATUS, LETS UNDERSTAND THE BOOKING PATTERN ACCROSS DIFFERENT CUSTOMER TYPES AND THEIR MOST PREFERRED HOTEL TYPE

-- BOOKING FREQUENCY FOR EACH CUSTOMER TYPE
	SELECT [Customer Type], 
	COUNT(*) BOOKING_FREQ
	FROM BookingData
	GROUP BY [Customer Type]
	ORDER BY BOOKING_FREQ DESC;

--WHAT IS THE BOOKING FREQUENCY OF DIFFERENT CUSTOMER TYPES ACCROSS THE TWO HOTEL TYPE
	SELECT [Customer Type], Hotel,
	COUNT(*) BOOKING_PATTERN
	FROM BookingData
	GROUP BY [Customer Type], Hotel
	ORDER BY BOOKING_PATTERN DESC;
					
--HOW MUCH REVENUE DOES EACH CUSTOMER TYPE BRING IN
	SELECT [CUSTOMER TYPE], 
	ROUND(SUM(REVENUE), 0) CUSTOMER_REVENUE
	FROM BookingData
	GROUP BY [Customer Type]
	ORDER BY CUSTOMER_REVENUE DESC;

--CUSTOMER TYPE REVENUE ACCROSS THE HOTEL TYPE
	SELECT [Customer Type], Hotel,
	ROUND(SUM(REVENUE), 2) TOTALREV
	FROM BookingData
	GROUP BY [Customer Type], Hotel
	ORDER BY TOTALREV DESC;

--CUSTOMER TYPE REVENUE LOSS ACCROSS THE HOTEL TYPE
	SELECT [Customer Type], Hotel,
	ROUND(SUM([Revenue Loss]), 0) REV_LOSS
	FROM BookingData
	GROUP BY [Customer Type], Hotel
	ORDER BY REV_LOSS;

--NOW THAT WE HAVE SEEN THE BOOKING PATTERN, REVENUE GENERATED AND REVENUE LOSS, LET US TRY AND UNDERSTAND WHY SO MUCH LOSS WAS RECORDED
	--WE CAN OBVIOUSLY SEE THAT THE LOSSES WERE SPREAD ACCROSS EACH HOTEL TYPE AND CUSTOMER TYPE, AND IT IS PROBABLY IN RELATION WITH THE CANCELLATION. SO THEN, LETS ANALYZE THE CANCELLATIONS BY CUSTOMER TYPE AND HOTEL TYPE
--BUT FIRST, LETS SEE THE CANCELLATION ON A GENERAL BASIS
	
--TOTAL CANCELLED AND NOT CANCELLED
	SELECT [Cancellation Status], 
	COUNT(*) CANCELLATION_TOTAL
	FROM BookingData
	GROUP BY [Cancellation Status];

--CANCELLATION BASED ON HOTEL TYPE
	SELECT Hotel, [Cancellation Status], 
	COUNT(*) STATUS_COUNT
	FROM BookingData
	GROUP BY Hotel, [Cancellation Status]
	ORDER BY STATUS_COUNT DESC;
--HERE WE CAN SEE THAT THE NUMBER OF CANCELLED BOKINGS FOR CITY IS ABOUT 40% OF THE TOTAL BOOKINGS FOR CITY, THIS IS TO TELL THAT CITY CUSTOMERS TEND TO CANCEL THEIR BOOKINGS MORE

--BASED ON CUSTOMER TYPE			
	SELECT [Customer Type], 
	[Cancellation Status], 
	COUNT([CANCELLATION STATUS]) STATUSCOUNT
	FROM BookingData	 
	GROUP BY [Customer Type], [Cancellation Status]
	ORDER BY STATUSCOUNT DESC;

--DOES THE CANCELLATION STATUS AFFECT THE REVENUE, LETS SEE HOW THEY ARE RELATED
	SELECT [Cancellation Status], 
	ROUND(SUM(REVENUE), 2) REV_BY_CANCELLATIONSTAT,
	ROUND(SUM([Revenue Loss]), 2) LOSS_BY_CANCELLATIONSTAT
	FROM BookingData
	GROUP BY [Cancellation Status]
	ORDER BY REV_BY_CANCELLATIONSTAT DESC, LOSS_BY_CANCELLATIONSTAT DESC;
--FROM THE ABOVE, WE CAN SEE THAT SOME REVENUE WAS GENERATED DUE TO CANCELLATION.

--GOOD TO KNOW THAT THE HOTEL MADE QUITE SOME REVENUE TOO FROM CANCELLATIONS, BUT WHY IS THIS SO, PROBABLY THERE IS A POLICY THAT SUPPORTS THIS. LETS TAKE A LOOK AT THE DEPOSIT TYPE THEN
--REVENUE AND REVENUE LOSS BY DEPOSIT TYPE
	SELECT [Deposit Type],
	ROUND(SUM(REVENUE), 2) REV_BY_DEPOSIT,
	ROUND(SUM([REVENUE LOSS]), 2) LOSS_BY_DEPOSIT
	FROM BookingData
	GROUP BY [Deposit Type]
	ORDER BY REV_BY_DEPOSIT DESC, LOSS_BY_DEPOSIT DESC;
--CLEARLY, WE CAN SEE THAT FROM THE THREE DEPOSIT TYPES, THE NO DEPOSIT AND REFUNDABLE TYPES RECORDED MORE LOSSES, LETS SEE THE DISTRIBUTION ACCROSS THE HOTEL TYPES, CANCELLATION STATUS AND CUSTOMERS TYPES
--DEPOSIT TYPE AND CANCELLATION
	SELECT [Deposit Type],
	[Cancellation Status], 
	ROUND(SUM(Revenue), 0) REVENUE,
	ROUND(SUM([Revenue Loss]), 0) REVENUE_LOSS,
	COUNT (*) COUNT_OF_CANCELLATION
	FROM BookingData	 
	GROUP BY [Deposit Type], [Cancellation Status];


--THE ANALYSIS ABOVE SHOWS FOR THAT THE NON-REFUNDALE AND NO DEPOSIT DEPOSIT TYPES, LOSSES WHERE RECORDED, WHILE THE NON-REFUNDABLE DPOSIT TYPE MADE THE HOTEL SOME COOL CASH
--ALTHOUGH THE REVENUE MADE FROM THE NON REFUNDABLE WAS NOT MUCH, WE CAN SEE THAT THE NO DEPOSIT TYPE MADE THE HOTEL A LOT OF LOSSES.

--NOW THAT WE HAVE SEEN THE BOOKING PATTERNS, REVENUE AND REVEUNE LOSS AND THE PROBABLE CAUSE FOR IT, LETS MOVE ON TO SEE IF WE CAN GENERATE MORE INSIGHTS FOR THE CANCELLATION, LET US GROUP THE BOOKING MONTHS INTO SEASON, THERE MIGHT BE A LINK
--GROUP BOOKING DATE INTO CLIMATE SEASONS AND FIND THE BOOKING PATTERN OF CUSTOMER TYPE AND HOTEL TYPE
--TOTAL BOOKINGS BY THE SEASONS
	WITH SEASONALBOOKINGS AS
	(SELECT 
	CASE 
    WHEN MONTH([Booking Date]) IN (3, 4, 5) THEN 'Spring'
    WHEN MONTH([Booking Date]) IN (6, 7, 8) THEN 'Summer'
    WHEN MONTH([Booking Date]) IN (9, 10, 11) THEN 'Fall'
    ELSE 'Winter'
	END AS SEASON
	FROM BookingData
	)
	SELECT SEASON, 
	COUNT(*) BOOKINGS_BY_SEASON
	FROM SEASONALBOOKINGS
	GROUP BY SEASON
	ORDER BY BOOKINGS_BY_SEASON DESC;
--WE CAN SEE THAT IN GENERAL, WINTER HAD MORE BOOKINGS THAN THE OTHER SEASONS, THIS MEANS THAT CUSTOMERS TEND TO BOOK MORE DURING THE WINTER SEASON

--LETS SEE THE DISTRIBUTION OF SEASONAL BOOKING BY HOTEL TYPE 
	WITH SEASONALBOOKINGS AS
	(SELECT 
	CASE 
    WHEN MONTH([Booking Date]) IN (3, 4, 5) THEN 'Spring'
    WHEN MONTH([Booking Date]) IN (6, 7, 8) THEN 'Summer'
    WHEN MONTH([Booking Date]) IN (9, 10, 11) THEN 'Fall'
    ELSE 'Winter'
	END AS SEASON,
	Hotel
	FROM BookingData
	)
	SELECT HOTEL, SEASON, 
	COUNT(*) BOOKINGS_BY_SEASON
	FROM SEASONALBOOKINGS
	GROUP BY SEASON, Hotel
	ORDER BY BOOKINGS_BY_SEASON DESC;
--FROM THE ANALYSIS ABOVE, WE CAN SEE THAT THERE WERE MORE BOOKINGS DURING THE WINTER SEASON FOR BOTH CITY AND RESORT, WITH CITY HAVIG THE HIGHEST NUMBER OF BOOKINGS. 

--LETS TAKE A LOOK AT SEASONAL CANCELLATIONS			
--SEASONAL CANCELLATION
	WITH SEASONALBOOKINGS AS
	(SELECT 
	CASE 
    WHEN MONTH([Booking Date]) IN (3, 4, 5) THEN 'Spring'
    WHEN MONTH([Booking Date]) IN (6, 7, 8) THEN 'Summer'
    WHEN MONTH([Booking Date]) IN (9, 10, 11) THEN 'Fall'
    ELSE 'Winter'
	END AS SEASON,
	[Cancellation Status]
	FROM BookingData
	)
	SELECT SEASON, [Cancellation Status],
	COUNT(*) CANCELLATION_BY_SEASON
	FROM SEASONALBOOKINGS
	GROUP BY SEASON, [Cancellation Status]
	ORDER BY SEASON DESC, CANCELLATION_BY_SEASON DESC;
--THIS ANALYSIS ALSO SHOW THAT WINTER STILL HAD MORE CANCELLATIONS THAN THE OTHERS. THAT IS PROBABLY BECAUSE IT HAD MORE BOOKINGS..

--LETS SEE THE PATTERN OF SEASONAL BOOKNGS BY CUSTOMER TYPE
	WITH SEASONALBOOKINGS AS
	(SELECT 
	CASE 
    WHEN MONTH([Booking Date]) IN (3, 4, 5) THEN 'Spring'
    WHEN MONTH([Booking Date]) IN (6, 7, 8) THEN 'Summer'
    WHEN MONTH([Booking Date]) IN (9, 10, 11) THEN 'Fall'
    ELSE 'Winter'
	END AS SEASON,
	[Customer Type]
	FROM BookingData
	)
	SELECT [Customer Type], SEASON, 
	COUNT(*) BOOKING_BY_SEASON
	FROM SEASONALBOOKINGS
	GROUP BY [Customer Type], SEASON
	ORDER BY BOOKING_BY_SEASON DESC;
--FROM THE ABOVE ANALYSIS, THE RESULT SHOWS THE DISTRIBUTION ON CUSTOMEER TYPES ACCROSS THE SEASONS, WITH TRANSIENT HAVING THE HIGHEST NUMBER OF BOOKINGS.

--NOW LETS RUN A PERCENTAGE RATING FOR CANCELLATION
--CANCELLATION RATE BY CUSTOMER TYPE
	WITH CANCELLATION_RATE AS
	(
	SELECT [Customer Type], [Cancellation Status],
	CONVERT(DECIMAL (10, 0), COUNT(*)) CANCELLATION_COUNT
	FROM BookingData
	GROUP BY [Cancellation Status], [Customer Type]
	)
	SELECT [Customer Type], [Cancellation Status],
	ROUND((CANCELLATION_COUNT * 100) / SUM(CANCELLATION_COUNT) OVER (PARTITION BY [CUSTOMER TYPE]), 2) CANCELLATION_PERCENTAGE
	FROM CANCELLATION_RATE;

-- SEASONAL CANCELLATION RATE
	WITH SEASONALBOOKINGS AS
	(SELECT SEASON, [CANCELLATION STATUS], CONVERT(DECIMAL (10,2), COUNT(*)) SEASONAL_CANCELLATION
	FROM (
	SELECT 
	CASE 
    WHEN MONTH([Booking Date]) IN (3, 4, 5) THEN 'Spring'
    WHEN MONTH([Booking Date]) IN (6, 7, 8) THEN 'Summer'
    WHEN MONTH([Booking Date]) IN (9, 10, 11) THEN 'Fall'
    ELSE 'Winter'
	END AS SEASON,
	[Cancellation Status]
	FROM BookingData
	) SUB GROUP BY SEASON, [Cancellation Status])
	SELECT SEASON, [Cancellation Status],
	ROUND((SEASONAL_CANCELLATION * 100) / SUM(SEASONAL_CANCELLATION) OVER (PARTITION BY [SEASON]), 2) CANCELLATION_PERCENTAGE
	FROM SEASONALBOOKINGS

--NOW THAT WE HAVE SEEN WHAT WE WANT, LET DO SOME ANALYSIS FOR DISTRIBUTION CHANNEL
--WHAT DISTRIBUTION CHANNEL BRINGS IN MORE REVENUE
	SELECT [Distribution Channel], 
	ROUND(SUM(REVENUE), 0) REVBYCHANNEL
	FROM BookingData
	GROUP BY [Distribution Channel]
	ORDER BY REVBYCHANNEL DESC;

--WHICH DISTRIBUTION CHANNEL INCURRED MORE LOSSES
	SELECT [Distribution Channel], 
	ROUND(SUM([REVENUE LOSS]), 2) LOSS_BY_CHANNEL
	FROM BookingData
	GROUP BY [Distribution Channel]
	ORDER BY LOSS_BY_CHANNEL;

--SHOW THE RELATIONSHIP BETWEEN DISTRIBUTION CHANNEL, CANCELLATION STATUS AND DEPOSIT TYPE
	SELECT [Distribution Channel], 
	([Cancellation Status]), 
	COUNT([Cancellation Status]) CANCELLATIONCOUNT
	FROM BookingData
	GROUP BY [Distribution Channel], [Cancellation Status]
	ORDER BY  [Distribution Channel] DESC;

--HOW DOES CANCELLATION STATUS AFFECT THE REVENUE FOR EACH DISTRIBUTION CHANNEL
	SELECT [Distribution Channel], 
	[Cancellation Status], 
	ROUND(SUM([REVENUE LOSS]), 0) REVLOSS,
	ROUND(SUM(REVENUE), 0) REVE
	FROM BookingData
	GROUP BY [Distribution Channel], [Cancellation Status]
	ORDER BY [Distribution Channel] DESC;



--FROM THE ANALYSIS ABOVE, WE CAN THEN MAKE RECOMMENDATIONS FOR THE HOTEL

	
	





	